# Transformer Anatomy

The Transformer architecture, introduced in the paper "Attention is All You Need" by Vaswani et al., 2017, has revolutionized the field of NLP. Unlike previous models that relied on recurrent or convolutional layers, Transformers use self-attention mechanisms to capture dependencies between words in a sentence, regardless of their distance.

### Key Components of the Transformer Architecture:

1. **Positional Encoding**: Adds information about the position of words in a sequence since the model itself does not inherently understand word order.
2. **Self-Attention Mechanism**: Allows the model to weigh the importance of each word in a sentence relative to all other words.
3. **Multi-Head Attention**: Enables the model to focus on different parts of the input simultaneously.
4. **Layer Normalization and Residual Connections**: Stabilizes training and helps with gradient flow.
5. **Feed-Forward Neural Networks**: Applies a point-wise feed-forward layer to each position independently and destilles the information further to output probabilities.

Let's explore each of these components in detail and understand how they work together to create powerful language models.

> **Bazzite-AI Setup Required**  
> Run `D0_00_Bazzite_AI_Setup.ipynb` first to verify GPU access.

## Self-Attention Mechanism

The self-attention mechanism is the core component of the Transformer architecture. It allows the model to dynamically assign different levels of importance to different words in a sentence when encoding a particular word.

### How Self-Attention Works:

1. **Input Embeddings**: Before we can apply self-attention, the input words must first be converted into embeddings (dense vector representations).
2. **Query, Key, and Value Vectors**: For each word, the model creates three vectors: a Query vector (Q), a Key vector (K), and a Value vector (V).
3. **Attention Scores**: The attention score is computed as the dot product of the Query vector of a word with the Key vectors of all words. This score determines how much focus should be on the other words.
4. **Weighted Sum**: Each word's output representation is computed as a weighted sum of the Value vectors, where the weights are the normalized attention scores.
5. **Softmax Normalization**: After the attention heads, the scores are passed through a softmax function to convert them into probabilities.

### Visualizing Self-Attention

Let's visualize how the self-attention mechanism works for a simple sentence.


In [1]:
# Import required libraries
import torch
import torch.nn.functional as F
import math

In [3]:
# Example sentence and tokens
sentence = "Transformers are revolutionary in NLP."
tokens = ["Transformers", "are", "revolutionary", "in", "NLP"]

In [6]:
# Embedding dimension
embedding_dim = 8

# Random input embeddings (for illustration purposes)
torch.manual_seed(42)
input_embeddings = torch.randn(len(tokens), embedding_dim)

In [7]:
# In this example we end up with a 5x8 matrix
input_embeddings

tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431, -1.6047],
        [-0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594, -0.7688,  0.7624],
        [ 1.6423, -0.1596, -0.4974,  0.4396, -0.7581,  1.0783,  0.8008,  1.6806],
        [ 0.0349,  0.3211,  1.5736, -0.8455,  1.3123,  0.6872, -1.0892, -0.3553],
        [-1.4181,  0.8963,  0.0499,  2.2667,  1.1790, -0.4345, -1.3864, -1.2862]])

In [4]:
# Initialize Query, Key, and Value weight matrices
Q = torch.randn(embedding_dim, embedding_dim)
K = torch.randn(embedding_dim, embedding_dim)
V = torch.randn(embedding_dim, embedding_dim)

NameError: name 'embedding_dim' is not defined

In [5]:
# Compute Query, Key, and Value vectors
queries = input_embeddings @ Q
keys = input_embeddings @ K
values = input_embeddings @ V

NameError: name 'input_embeddings' is not defined

In [2]:
# Calculate attention scores using dot product of queries and keys
attention_scores = queries @ keys.T

# Apply softmax to normalize the scores
attention_weights = F.softmax(attention_scores/math.sqrt(embedding_dim), dim=-1)

NameError: name 'queries' is not defined

In [8]:
# Compute the weighted sum of values
output = attention_weights @ values

# Display the attention weights
print("Attention Weights:\n", attention_weights)

NameError: name 'attention_weights' is not defined

## Multi-Head Attention

The multi-head attention mechanism allows the model to focus on different parts of the input simultaneously. Instead of having a single attention mechanism, the model uses multiple attention "heads" in parallel. Each head can learn different aspects of the input.

### How Multi-Head Attention Works:

1. The input is projected into multiple sets of Query, Key, and Value vectors.
2. Each set of vectors is processed independently through a self-attention mechanism.
3. The outputs from each head are concatenated and projected back into a single vector space.

This approach provides the model with a richer understanding of the input by capturing different types of relationships between words.

### Example: Multi-Head Attention
Let's visualize how multi-head attention works using multiple attention heads.


In [9]:
# Number of attention heads
num_heads = 2

# Initialize weight matrices for each head
Q_heads = [torch.randn(embedding_dim, embedding_dim) for _ in range(num_heads)]
K_heads = [torch.randn(embedding_dim, embedding_dim) for _ in range(num_heads)]
V_heads = [torch.randn(embedding_dim, embedding_dim) for _ in range(num_heads)]

In [10]:
# Compute outputs for each head
head_outputs = []
for i in range(num_heads):
    queries = input_embeddings @ Q_heads[i]
    keys = input_embeddings @ K_heads[i]
    values = input_embeddings @ V_heads[i]
    
    # Calculate attention scores and apply softmax
    attention_scores = queries @ keys.T
    attention_weights = F.softmax(attention_scores/math.sqrt(embedding_dim), dim=-1)
    
    # Compute the weighted sum of values
    output = attention_weights @ values
    head_outputs.append(output)

In [11]:
# Concatenate outputs from all heads
multi_head_output = torch.cat(head_outputs, dim=-1)

# Display multi-head attention output
print("Multi-Head Attention Output:\n", multi_head_output)

Multi-Head Attention Output:
 tensor([[-3.2237e-01,  4.6591e+00, -9.6314e+00, -2.9663e+00,  3.3225e+00,
          2.9357e+00, -2.3207e+00, -2.0601e+00,  2.7245e+00, -1.1831e+00,
          5.6527e+00,  2.6269e-01,  4.7597e+00, -4.0497e-01, -1.5315e+00,
         -3.2463e+00],
        [ 1.0108e+00, -4.0638e+00,  2.3292e+00, -2.8314e-01,  3.4551e+00,
          5.5581e+00,  5.0915e+00,  1.3194e+00, -6.4749e+00,  5.8671e+00,
          3.8078e+00, -2.3065e-01, -2.7182e+00, -1.3306e+00, -2.0265e+00,
          3.9932e-01],
        [-3.4254e-01,  4.6145e+00, -9.4725e+00, -2.9815e+00,  3.2473e+00,
          2.8808e+00, -2.3042e+00, -1.9888e+00,  1.6466e+00, -1.7977e+00,
         -1.3634e+00,  1.1788e-01, -2.7043e+00,  1.2903e+00,  2.6171e+00,
          4.7654e+00],
        [-8.3613e-03,  2.6027e+00, -6.7415e+00, -2.3407e+00,  3.3221e+00,
          3.5544e+00, -6.2675e-01, -1.1993e+00,  2.7992e+00, -4.4668e+00,
         -4.1611e+00,  4.2510e-01, -5.3059e+00,  2.4657e+00,  4.6805e+00,
          6.6

## Feed-Forward Neural Networks

Each position's output from the multi-head attention mechanism is passed through a point-wise feed-forward neural network. This consists of two linear transformations with a ReLU activation in between.

### Example: Feed-Forward Network
Let's implement a simple feed-forward network.

In [12]:
# Define feed-forward neural network
class FeedForwardNN(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super(FeedForwardNN, self).__init__()
        self.linear1 = torch.nn.Linear(input_dim, hidden_dim)
        self.relu = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(hidden_dim, input_dim)
    
    def forward(self, x):
        return self.linear2(self.relu(self.linear1(x)))

In [13]:
# Instantiate and apply the feed-forward network
ffn = FeedForwardNN(input_dim=embedding_dim * num_heads, hidden_dim=32)
ffn_output = ffn(multi_head_output)

# Display the feed-forward network output
print("Feed-Forward Network Output:\n", ffn_output)

Feed-Forward Network Output:
 tensor([[-0.1076, -1.1561, -0.2368,  0.8209,  0.9425,  0.8352,  0.1717,  0.3996,
         -0.5560,  0.5732,  1.0187, -1.3614,  0.8661, -0.9439, -0.5560, -1.0347],
        [-0.8371,  0.5195,  1.0020,  0.8108, -0.2805,  1.2257, -1.6926,  2.2672,
         -0.3883,  1.3553, -0.2897, -1.1592,  0.0278, -0.1767, -0.2364, -0.0273],
        [-0.8777, -0.5523, -0.6139, -0.7321,  1.3447,  0.6218,  1.4753,  1.1127,
          0.3491, -0.4577,  0.2886, -0.6492,  1.5801, -1.6984,  0.0520, -0.7382],
        [-1.5672, -0.7098, -0.1675, -1.0434,  0.8221,  0.5423,  1.9750,  1.2772,
          0.7321, -0.5789, -0.1112,  0.3048,  1.4322, -1.9399,  0.0625, -0.1988],
        [-1.0258,  0.3024,  0.9928, -0.9082,  0.7688,  1.2261, -0.4238,  1.2061,
          0.2265,  0.5295,  0.1424, -1.2343, -0.9645,  0.4392,  0.1343, -0.5169]],
       grad_fn=<AddmmBackward0>)

## Layer Normalization and Residual Connections

Layer normalization is used to stabilize training by normalizing the inputs to each layer. Residual connections help maintain gradient flow through the network, enabling deeper architectures.

### Example: Adding Layer Normalization and Residual Connections
Let's see how these components are added to the Transformer block.


In [14]:
# Define Layer Normalization
layer_norm = torch.nn.LayerNorm(embedding_dim * num_heads)

# Add residual connection and apply layer normalization
residual_output = layer_norm(multi_head_output + ffn_output)

# Display the final output with residual connection
print("Output with Residual Connections:\n", residual_output)

Output with Residual Connections:
 tensor([[-0.1115,  0.8620, -2.4476, -0.5361,  1.0506,  0.9283, -0.5369, -0.4160,
          0.5317, -0.1560,  1.6463, -0.2770,  1.3875, -0.3389, -0.5217, -1.0647],
        [-0.1859, -1.1866,  0.6639, -0.0906,  0.6218,  1.5932,  0.6822,  0.7327,
         -2.0799,  1.7112,  0.7142, -0.6068, -0.9568, -0.6383, -0.8417, -0.1325],
        [-0.3199,  1.1613, -2.8059, -1.0190,  1.3098,  1.0044, -0.2102, -0.2234,
          0.5818, -0.6101, -0.2791, -0.1267, -0.2930, -0.0922,  0.7707,  1.1515],
        [-0.4497,  0.4527, -1.8375, -0.9203,  1.0386,  1.0262,  0.3111, -0.0195,
          0.8791, -1.3527, -1.1514,  0.1501, -1.0477,  0.0970,  1.1944,  1.6297],
        [-0.2064,  0.6243, -0.1769, -0.9248,  0.6465,  1.5385, -1.2563,  1.2464,
         -1.5414,  1.2477,  0.0650, -0.3923, -1.9461,  0.0406,  0.0999,  0.9353]],
       grad_fn=<NativeLayerNormBackward0>)

## Positional Encoding

Since the Transformer does not inherently capture the order of words, positional encoding is added to provide the model with information about the relative position of words in a sentence.

### Example: Implementing Positional Encoding
Let's implement positional encoding for a sequence of words.


In [15]:
import numpy as np

def positional_encoding(seq_len, model_dim):
    pos_enc = np.zeros((seq_len, model_dim))
    for pos in range(seq_len):
        for i in range(0, model_dim, 2):
            pos_enc[pos, i] = np.sin(pos / (10000 ** (2 * i / model_dim)))
            pos_enc[pos, i + 1] = np.cos(pos / (10000 ** (2 * i / model_dim)))
    return torch.tensor(pos_enc, dtype=torch.float)

In [17]:
# Random input embeddings (for illustration purposes)
torch.manual_seed(42)
input_embeddings = torch.randn(len(tokens), embedding_dim)

In [16]:
# Apply positional encoding
position_encodings = positional_encoding(len(tokens), embedding_dim)

# Add positional encoding to input embeddings
encoded_input = input_embeddings + position_encodings

print("Positional Encodings:\n", position_encodings)
print("Encoded Input with Positional Information:\n", encoded_input)

Positional Encodings:
 tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9998e-03,  9.9995e-01,  1.0000e-04,
          1.0000e+00,  1.0000e-06,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9999e-02,  9.9980e-01,  2.0000e-04,
          1.0000e+00,  2.0000e-06,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  2.9996e-02,  9.9955e-01,  3.0000e-04,
          1.0000e+00,  3.0000e-06,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  3.9989e-02,  9.9920e-01,  4.0000e-04,
          1.0000e+00,  4.0000e-06,  1.0000e+00]])
Encoded Input with Positional Information:
 tensor([[ 1.9269,  2.4873,  0.9007, -1.1055,  0.6784, -0.2345, -0.0431, -0.6047],
        [ 0.0893,  2.1890, -0.3825, -0.4037, -0.7278,  0.4406, -0.7688,  1.7624],
        [ 2.5516, -0.5757, -0.4774,  1.4394, -0.7579,  2.0783,  0.8008,  2.6806],
        [ 0.1760, -0.6689,  1.6036,  0.1541,  1.3126,  1.6872, -1.0892,

## Conclusion

In this notebook, we explored the key components of the Transformer architecture, including self-attention, multi-head attention, feed-forward networks, layer normalization, and positional encoding. These components work together to form the basis of modern NLP models.

In [18]:
# Shut down the kernel to release memory
import IPython

app = IPython.Application.instance()
app.kernel.do_shutdown(restart=False)

{'status': 'ok', 'restart': False}